import React, { useState, useEffect } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Sidebar from '../components/sidebar'
import Shorts from '../components/shorts'
import File from '../components/data/file'
import Suggestions from '../components/suggestions'

export const getStaticProps  = async ()=>{
  const response = await fetch(`https://api.unsplash.com/photos/random?count=6&client_id=npxnEdaLlHiFXJTXd9gAON2o9v0bV7ztrUTfLBrQD84`)
  const data = await response.json(); 
  console.log("response............",data);
  return { props: { data } }
}
export default function Home({data}) {
  console.log("data",data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Instagram Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className='container-fluid'>
          <div className='row vh-100'>
            <div className='col-2 border-end'>
              <Sidebar />
            </div>

            <div className='col-10'>
              <div className='row vh-100 overflow-auto'>
                <div className='col-7'>
                  <div className="row">
                    <div className='col-8 offset-4 pt-3'>
                      <Shorts data = {data} />
                      <File data = {data} />
                    </div>
                  </div>
                </div>

                <div className='col-4 px-5 pt-4'>
                  <Suggestions data = {data} />
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
